
import React, { Fragment, useEffect, useState } from 'react';
import { formateDate } from '../utils';


const Weather = () => {
  
  const [weather, setWeather] = useState({
    location: {
      name: 'London',
      region: 'City of London, Greater London',
      country: 'United Kingdom',
      lat: 51.5171,
      lon: -0.1062,
      tz_id: 'Europe/London',
      localtime_epoch: 1773138958,
      localtime: '2026-03-10 10:35',
    },
    current: {
      last_updated_epoch: 1773138600,
      last_updated: '2026-03-10 10:30',
      temp_c: 11.2,
      temp_f: 52.2,
      is_day: 1,
      condition: {
        text: 'Partly cloudy',
        icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
        code: 1003,
      },
      wind_mph: 6,
      wind_kph: 9.7,
      wind_degree: 236,
      wind_dir: 'WSW',
      pressure_mb: 1015,
      pressure_in: 29.97,
      precip_mm: 0,
      precip_in: 0,
      humidity: 71,
      cloud: 75,
      feelslike_c: 10.1,
      feelslike_f: 50.2,
      windchill_c: 8.8,
      windchill_f: 47.8,
      heatindex_c: 10.1,
      heatindex_f: 50.2,
      dewpoint_c: 6,
      dewpoint_f: 42.8,
      vis_km: 10,
      vis_miles: 6,
      uv: 1.4,
      gust_mph: 7.4,
      gust_kph: 11.9,
      short_rad: 0,
      diff_rad: 0,
      dni: 0,
      gti: 0,
    },
    forecast: {
      forecastday: [
        {
          date: '2026-03-10',
          date_epoch: 1773100800,
          day: {
            maxtemp_c: 13.2,
            maxtemp_f: 55.7,
            mintemp_c: 7.5,
            mintemp_f: 45.4,
            avgtemp_c: 9.8,
            avgtemp_f: 49.7,
            maxwind_mph: 13.2,
            maxwind_kph: 21.2,
            totalprecip_mm: 0.14,
            totalprecip_in: 0.01,
            totalsnow_cm: 0,
            avgvis_km: 8,
            avgvis_miles: 4,
            avghumidity: 81,
            daily_will_it_rain: 1,
            daily_chance_of_rain: 87,
            daily_will_it_snow: 0,
            daily_chance_of_snow: 0,
            condition: {
              text: 'Patchy rain nearby',
              icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
              code: 1063,
            },
            uv: 0.5,
          },
          astro: {
            sunrise: '06:26 AM',
            sunset: '05:56 PM',
            moonrise: '01:32 AM',
            moonset: '08:31 AM',
            moon_phase: 'Waning Gibbous',
            moon_illumination: 63,
            is_moon_up: 0,
            is_sun_up: 0,
          },
          hour: [
            {
              time_epoch: 1773100800,
              time: '2026-03-10 00:00',
              temp_c: 9.1,
              temp_f: 48.3,
              is_day: 0,
              condition: {
                text: 'Mist',
                icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
                code: 1030,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 218,
              wind_dir: 'SW',
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 95,
              cloud: 79,
              feelslike_c: 8.3,
              feelslike_f: 46.9,
              windchill_c: 8.3,
              windchill_f: 46.9,
              heatindex_c: 9.1,
              heatindex_f: 48.3,
              dewpoint_c: 8.2,
              dewpoint_f: 46.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 6.6,
              gust_kph: 10.7,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773104400,
              time: '2026-03-10 01:00',
              temp_c: 8.7,
              temp_f: 47.7,
              is_day: 0,
              condition: {
                text: 'Mist',
                icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
                code: 1030,
              },
              wind_mph: 3.8,
              wind_kph: 6.1,
              wind_degree: 214,
              wind_dir: 'SW',
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 96,
              cloud: 61,
              feelslike_c: 8,
              feelslike_f: 46.3,
              windchill_c: 8,
              windchill_f: 46.3,
              heatindex_c: 8.7,
              heatindex_f: 47.7,
              dewpoint_c: 8.1,
              dewpoint_f: 46.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 6.5,
              gust_kph: 10.4,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773108000,
              time: '2026-03-10 02:00',
              temp_c: 8.4,
              temp_f: 47.2,
              is_day: 0,
              condition: {
                text: 'Mist',
                icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
                code: 1030,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 217,
              wind_dir: 'SW',
              pressure_mb: 1016,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 96,
              cloud: 80,
              feelslike_c: 7.6,
              feelslike_f: 45.6,
              windchill_c: 7.6,
              windchill_f: 45.6,
              heatindex_c: 8.5,
              heatindex_f: 47.2,
              dewpoint_c: 7.9,
              dewpoint_f: 46.3,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 7,
              gust_kph: 11.2,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773111600,
              time: '2026-03-10 03:00',
              temp_c: 8.5,
              temp_f: 47.3,
              is_day: 0,
              condition: {
                text: 'Mist',
                icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
                code: 1030,
              },
              wind_mph: 4,
              wind_kph: 6.5,
              wind_degree: 214,
              wind_dir: 'SW',
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 96,
              cloud: 68,
              feelslike_c: 7.6,
              feelslike_f: 45.8,
              windchill_c: 7.6,
              windchill_f: 45.8,
              heatindex_c: 8.5,
              heatindex_f: 47.3,
              dewpoint_c: 7.9,
              dewpoint_f: 46.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 6.8,
              gust_kph: 10.9,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773115200,
              time: '2026-03-10 04:00',
              temp_c: 8.6,
              temp_f: 47.5,
              is_day: 0,
              condition: {
                text: 'Mist',
                icon: '//cdn.weatherapi.com/weather/64x64/night/143.png',
                code: 1030,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 240,
              wind_dir: 'WSW',
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 94,
              cloud: 67,
              feelslike_c: 7.5,
              feelslike_f: 45.5,
              windchill_c: 7.5,
              windchill_f: 45.5,
              heatindex_c: 8.6,
              heatindex_f: 47.5,
              dewpoint_c: 7.8,
              dewpoint_f: 46,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 7.4,
              gust_kph: 12,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773118800,
              time: '2026-03-10 05:00',
              temp_c: 8.5,
              temp_f: 47.2,
              is_day: 0,
              condition: {
                text: 'Partly Cloudy ',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 4.7,
              wind_kph: 7.6,
              wind_degree: 249,
              wind_dir: 'WSW',
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 93,
              cloud: 61,
              feelslike_c: 7.3,
              feelslike_f: 45.1,
              windchill_c: 7.3,
              windchill_f: 45.1,
              heatindex_c: 8.5,
              heatindex_f: 47.2,
              dewpoint_c: 7.4,
              dewpoint_f: 45.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.2,
              gust_kph: 11.6,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773122400,
              time: '2026-03-10 06:00',
              temp_c: 7.9,
              temp_f: 46.3,
              is_day: 0,
              condition: {
                text: 'Cloudy ',
                icon: '//cdn.weatherapi.com/weather/64x64/night/119.png',
                code: 1006,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 260,
              wind_dir: 'W',
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 94,
              cloud: 68,
              feelslike_c: 6.6,
              feelslike_f: 43.9,
              windchill_c: 6.6,
              windchill_f: 43.9,
              heatindex_c: 7.9,
              heatindex_f: 46.3,
              dewpoint_c: 7,
              dewpoint_f: 44.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.6,
              gust_kph: 12.3,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773126000,
              time: '2026-03-10 07:00',
              temp_c: 7.5,
              temp_f: 45.4,
              is_day: 1,
              condition: {
                text: 'Mist',
                icon: '//cdn.weatherapi.com/weather/64x64/day/143.png',
                code: 1030,
              },
              wind_mph: 4.3,
              wind_kph: 6.8,
              wind_degree: 258,
              wind_dir: 'WSW',
              pressure_mb: 1017,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 94,
              cloud: 66,
              feelslike_c: 6.3,
              feelslike_f: 43.4,
              windchill_c: 6.3,
              windchill_f: 43.4,
              heatindex_c: 7.5,
              heatindex_f: 45.4,
              dewpoint_c: 6.6,
              dewpoint_f: 43.9,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 2,
              vis_miles: 1,
              gust_mph: 6.6,
              gust_kph: 10.7,
              uv: 0.1,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773129600,
              time: '2026-03-10 08:00',
              temp_c: 8.2,
              temp_f: 46.7,
              is_day: 1,
              condition: {
                text: 'Partly Cloudy ',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 4.9,
              wind_kph: 7.9,
              wind_degree: 257,
              wind_dir: 'WSW',
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 88,
              cloud: 52,
              feelslike_c: 6.9,
              feelslike_f: 44.3,
              windchill_c: 6.9,
              windchill_f: 44.3,
              heatindex_c: 8.2,
              heatindex_f: 46.7,
              dewpoint_c: 6.4,
              dewpoint_f: 43.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.7,
              gust_kph: 10.8,
              uv: 0.4,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773133200,
              time: '2026-03-10 09:00',
              temp_c: 9.2,
              temp_f: 48.5,
              is_day: 1,
              condition: {
                text: 'Cloudy ',
                icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
                code: 1006,
              },
              wind_mph: 5.4,
              wind_kph: 8.6,
              wind_degree: 248,
              wind_dir: 'WSW',
              pressure_mb: 1017,
              pressure_in: 30.03,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 81,
              cloud: 70,
              feelslike_c: 7.9,
              feelslike_f: 46.3,
              windchill_c: 7.9,
              windchill_f: 46.3,
              heatindex_c: 9.2,
              heatindex_f: 48.5,
              dewpoint_c: 6.2,
              dewpoint_f: 43.1,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 6.8,
              gust_kph: 10.9,
              uv: 0.8,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773136800,
              time: '2026-03-10 10:00',
              temp_c: 11.2,
              temp_f: 52.2,
              is_day: 1,
              condition: {
                text: 'Partly cloudy',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 6,
              wind_kph: 9.7,
              wind_degree: 236,
              wind_dir: 'WSW',
              pressure_mb: 1015,
              pressure_in: 29.97,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 71,
              cloud: 75,
              feelslike_c: 8.8,
              feelslike_f: 47.8,
              windchill_c: 8.8,
              windchill_f: 47.8,
              heatindex_c: 10.1,
              heatindex_f: 50.2,
              dewpoint_c: 6,
              dewpoint_f: 42.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 7.4,
              gust_kph: 11.9,
              uv: 1.4,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773140400,
              time: '2026-03-10 11:00',
              temp_c: 10.5,
              temp_f: 50.9,
              is_day: 1,
              condition: {
                text: 'Partly Cloudy ',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 6.5,
              wind_kph: 10.4,
              wind_degree: 225,
              wind_dir: 'SW',
              pressure_mb: 1016,
              pressure_in: 30.02,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 74,
              cloud: 42,
              feelslike_c: 9.2,
              feelslike_f: 48.5,
              windchill_c: 9.2,
              windchill_f: 48.5,
              heatindex_c: 10.5,
              heatindex_f: 50.9,
              dewpoint_c: 6,
              dewpoint_f: 42.8,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 8.1,
              gust_kph: 13,
              uv: 1.9,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773144000,
              time: '2026-03-10 12:00',
              temp_c: 11.6,
              temp_f: 52.9,
              is_day: 1,
              condition: {
                text: 'Cloudy ',
                icon: '//cdn.weatherapi.com/weather/64x64/day/119.png',
                code: 1006,
              },
              wind_mph: 7.6,
              wind_kph: 12.2,
              wind_degree: 222,
              wind_dir: 'SW',
              pressure_mb: 1016,
              pressure_in: 30.01,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 69,
              cloud: 67,
              feelslike_c: 10.2,
              feelslike_f: 50.4,
              windchill_c: 10.2,
              windchill_f: 50.4,
              heatindex_c: 11.6,
              heatindex_f: 52.9,
              dewpoint_c: 6.2,
              dewpoint_f: 43.2,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 9,
              gust_kph: 14.5,
              uv: 2,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773147600,
              time: '2026-03-10 13:00',
              temp_c: 12.7,
              temp_f: 54.9,
              is_day: 1,
              condition: {
                text: 'Patchy rain nearby',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 8.7,
              wind_kph: 14,
              wind_degree: 223,
              wind_dir: 'SW',
              pressure_mb: 1015,
              pressure_in: 29.99,
              precip_mm: 0.01,
              precip_in: 0,
              snow_cm: 0,
              humidity: 64,
              cloud: 100,
              feelslike_c: 11.4,
              feelslike_f: 52.4,
              windchill_c: 11.4,
              windchill_f: 52.4,
              heatindex_c: 12.7,
              heatindex_f: 54.9,
              dewpoint_c: 6.1,
              dewpoint_f: 42.9,
              will_it_rain: 0,
              chance_of_rain: 62,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 10.3,
              gust_kph: 16.6,
              uv: 1.9,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773151200,
              time: '2026-03-10 14:00',
              temp_c: 13,
              temp_f: 55.4,
              is_day: 1,
              condition: {
                text: 'Patchy rain nearby',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 9.6,
              wind_kph: 15.5,
              wind_degree: 221,
              wind_dir: 'SW',
              pressure_mb: 1015,
              pressure_in: 29.96,
              precip_mm: 0.1,
              precip_in: 0,
              snow_cm: 0,
              humidity: 60,
              cloud: 68,
              feelslike_c: 11.6,
              feelslike_f: 52.8,
              windchill_c: 11.6,
              windchill_f: 52.8,
              heatindex_c: 13,
              heatindex_f: 55.4,
              dewpoint_c: 5.4,
              dewpoint_f: 41.8,
              will_it_rain: 1,
              chance_of_rain: 100,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 12,
              gust_kph: 19.3,
              uv: 1.4,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773154800,
              time: '2026-03-10 15:00',
              temp_c: 13.2,
              temp_f: 55.7,
              is_day: 1,
              condition: {
                text: 'Patchy rain nearby',
                icon: '//cdn.weatherapi.com/weather/64x64/day/176.png',
                code: 1063,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 217,
              wind_dir: 'SW',
              pressure_mb: 1014,
              pressure_in: 29.95,
              precip_mm: 0.03,
              precip_in: 0,
              snow_cm: 0,
              humidity: 58,
              cloud: 64,
              feelslike_c: 11.6,
              feelslike_f: 52.8,
              windchill_c: 11.6,
              windchill_f: 52.8,
              heatindex_c: 13.2,
              heatindex_f: 55.7,
              dewpoint_c: 5.1,
              dewpoint_f: 41.1,
              will_it_rain: 0,
              chance_of_rain: 69,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.1,
              gust_kph: 22.7,
              uv: 0.9,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773158400,
              time: '2026-03-10 16:00',
              temp_c: 12.9,
              temp_f: 55.2,
              is_day: 1,
              condition: {
                text: 'Partly Cloudy ',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 11.2,
              wind_kph: 18,
              wind_degree: 212,
              wind_dir: 'SSW',
              pressure_mb: 1014,
              pressure_in: 29.94,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 61,
              cloud: 37,
              feelslike_c: 11.2,
              feelslike_f: 52.1,
              windchill_c: 11.2,
              windchill_f: 52.1,
              heatindex_c: 12.9,
              heatindex_f: 55.2,
              dewpoint_c: 5.6,
              dewpoint_f: 42,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14,
              gust_kph: 22.5,
              uv: 0.4,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773162000,
              time: '2026-03-10 17:00',
              temp_c: 11.7,
              temp_f: 53,
              is_day: 1,
              condition: {
                text: 'Partly Cloudy ',
                icon: '//cdn.weatherapi.com/weather/64x64/day/116.png',
                code: 1003,
              },
              wind_mph: 11,
              wind_kph: 17.6,
              wind_degree: 209,
              wind_dir: 'SSW',
              pressure_mb: 1014,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 68,
              cloud: 29,
              feelslike_c: 9.7,
              feelslike_f: 49.4,
              windchill_c: 9.7,
              windchill_f: 49.4,
              heatindex_c: 11.7,
              heatindex_f: 53,
              dewpoint_c: 6,
              dewpoint_f: 42.7,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.6,
              gust_kph: 23.4,
              uv: 0.1,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773165600,
              time: '2026-03-10 18:00',
              temp_c: 10.3,
              temp_f: 50.5,
              is_day: 0,
              condition: {
                text: 'Partly Cloudy ',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 10.5,
              wind_kph: 16.9,
              wind_degree: 208,
              wind_dir: 'SSW',
              pressure_mb: 1014,
              pressure_in: 29.93,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 75,
              cloud: 30,
              feelslike_c: 8,
              feelslike_f: 46.4,
              windchill_c: 8,
              windchill_f: 46.4,
              heatindex_c: 10.3,
              heatindex_f: 50.5,
              dewpoint_c: 6.1,
              dewpoint_f: 43,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 15,
              gust_kph: 24.2,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773169200,
              time: '2026-03-10 19:00',
              temp_c: 9.5,
              temp_f: 49,
              is_day: 0,
              condition: {
                text: 'Partly Cloudy ',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 10.1,
              wind_kph: 16.2,
              wind_degree: 204,
              wind_dir: 'SSW',
              pressure_mb: 1013,
              pressure_in: 29.92,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 81,
              cloud: 27,
              feelslike_c: 7.1,
              feelslike_f: 44.8,
              windchill_c: 7.1,
              windchill_f: 44.8,
              heatindex_c: 9.5,
              heatindex_f: 49,
              dewpoint_c: 6.3,
              dewpoint_f: 43.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.4,
              gust_kph: 23.1,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773172800,
              time: '2026-03-10 20:00',
              temp_c: 9,
              temp_f: 48.1,
              is_day: 0,
              condition: {
                text: 'Clear ',
                icon: '//cdn.weatherapi.com/weather/64x64/night/113.png',
                code: 1000,
              },
              wind_mph: 10.3,
              wind_kph: 16.6,
              wind_degree: 203,
              wind_dir: 'SSW',
              pressure_mb: 1013,
              pressure_in: 29.91,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 84,
              cloud: 25,
              feelslike_c: 6.4,
              feelslike_f: 43.6,
              windchill_c: 6.4,
              windchill_f: 43.6,
              heatindex_c: 9,
              heatindex_f: 48.1,
              dewpoint_c: 6.5,
              dewpoint_f: 43.6,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 14.9,
              gust_kph: 23.9,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773176400,
              time: '2026-03-10 21:00',
              temp_c: 8.8,
              temp_f: 47.8,
              is_day: 0,
              condition: {
                text: 'Partly Cloudy ',
                icon: '//cdn.weatherapi.com/weather/64x64/night/116.png',
                code: 1003,
              },
              wind_mph: 11,
              wind_kph: 17.6,
              wind_degree: 203,
              wind_dir: 'SSW',
              pressure_mb: 1012,
              pressure_in: 29.9,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 85,
              cloud: 39,
              feelslike_c: 6.1,
              feelslike_f: 42.9,
              windchill_c: 6.1,
              windchill_f: 42.9,
              heatindex_c: 8.8,
              heatindex_f: 47.8,
              dewpoint_c: 6.4,
              dewpoint_f: 43.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 16.2,
              gust_kph: 26,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773180000,
              time: '2026-03-10 22:00',
              temp_c: 8.8,
              temp_f: 47.8,
              is_day: 0,
              condition: {
                text: 'Overcast ',
                icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
                code: 1009,
              },
              wind_mph: 12.3,
              wind_kph: 19.8,
              wind_degree: 201,
              wind_dir: 'SSW',
              pressure_mb: 1012,
              pressure_in: 29.87,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 85,
              cloud: 95,
              feelslike_c: 5.8,
              feelslike_f: 42.5,
              windchill_c: 5.8,
              windchill_f: 42.5,
              heatindex_c: 8.8,
              heatindex_f: 47.8,
              dewpoint_c: 6.4,
              dewpoint_f: 43.5,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 18.2,
              gust_kph: 29.3,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
            {
              time_epoch: 1773183600,
              time: '2026-03-10 23:00',
              temp_c: 9.1,
              temp_f: 48.5,
              is_day: 0,
              condition: {
                text: 'Overcast ',
                icon: '//cdn.weatherapi.com/weather/64x64/night/122.png',
                code: 1009,
              },
              wind_mph: 13.2,
              wind_kph: 21.2,
              wind_degree: 205,
              wind_dir: 'SSW',
              pressure_mb: 1011,
              pressure_in: 29.85,
              precip_mm: 0,
              precip_in: 0,
              snow_cm: 0,
              humidity: 82,
              cloud: 93,
              feelslike_c: 6.2,
              feelslike_f: 43.1,
              windchill_c: 6.2,
              windchill_f: 43.1,
              heatindex_c: 9.2,
              heatindex_f: 48.5,
              dewpoint_c: 6.3,
              dewpoint_f: 43.4,
              will_it_rain: 0,
              chance_of_rain: 0,
              will_it_snow: 0,
              chance_of_snow: 0,
              vis_km: 10,
              vis_miles: 6,
              gust_mph: 19.5,
              gust_kph: 31.3,
              uv: 0,
              short_rad: 0,
              diff_rad: 0,
              dni: 0,
              gti: 0,
            },
          ],
        },
      ],
    },
  });

  
  // useEffect(() => {
  //   async function get_weather() {
  //     try {
  //       const response = await fetch(
  //         'https://api.weatherapi.com/v1/forecast.json?key=83ba5181d2434bd6861103130261003&q=London&days=1&aqi=no&alerts=no',
  //       );

  //       if (!response.ok) throw new Error('Ошибка сети');

  //       const data = await response.json();

  //       console.log(Object.values(data));
  //       setWeather(data);
  //     } catch (error) {
  //       console.error('Произошла ошибка:', error);
  //     }
  //   }

  //   get_weather();
  // }, []);
  console.log(weather.location.localtime.split(' ')[0]);
  return (
    <section className="weather-widget">
      <div className="weather-widget__main">
        <div className="weather-widget__info">
          <h2 className="weather-widget__city">{weather.location.name}</h2>
          <p className="weather-widget__date">{formateDate(weather.location.localtime)}</p>
          <div className="weather-widget__condition">
            <img
              src={weather.current.condition.icon}
              alt={weather.current.condition.text}
              className="weather-widget__icon"
            />
            <span className="weather-widget__status">{weather.current.condition.text}</span>
          </div>
        </div>

        <div className="weather-widget__temp-block">
          <span className="weather-widget__current-temp">{Math.round(weather.current.temp_c)}°</span>
          <div className="weather-widget__range">
            <span className="high">{Math.round(weather.forecast.forecastday[0].day.maxtemp_c)}°</span> / <span className="low">{Math.round(weather.forecast.forecastday[0].day.mintemp_c)}°</span>
          </div>
        </div>
      </div>

      <nav className="weather-widget__nav">
        <a href="#" className="active">
          Hourly
        </a>
        <a href="#">Daily</a>
      </nav>

      <div className="weather-widget__hourly">
        {weather.forecast.forecastday.length !== 0 &&
          weather.forecast.forecastday[0].hour.map((el,id) => (
            <Fragment key={id}>
              <div className="forecast-item " >
                <span className="forecast-item__time">{el.time.split(' ')[1]}</span>
                <img
                  src={el.condition.icon}
                  alt={el.condition.text}
                  className="forecast-item__icon"
                />
                <p className="forecast-item__temp">{`${Math.round(el.temp_c)}°`}</p>
              </div>
            </Fragment>
          ))}
      </div>
    </section>
  );
};

export default Weather;
